# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_waitinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglistentry',
            name='campaign',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='waitinglistentry',
            name='referrer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='kind',
            field=models.IntegerField(choices=[(0, 'text field'), (1, 'textarea'), (2, 'radio choices'), (3, 'checkbox field (can select multiple answers'), (4, 'boolean field')]),
        ),
    ]
